### ISSUE TITLE
core.optimization.Minimizer: (0) [ WARNING ] LBFGS MAX CYCLES 25 EXCEEDED, BUT FUNC NOT CONVERGED! 

### ISSUE THREAD

**Issue by YangPH0624** [gfzhou/OpenVS#8]
Could you please let me know if this issue is serious, or if it can be safely ignored? Thank you!

**Comment by YangPH0624** [comment]
![Uploading 1730710370273.png…]()

**Comment by YangPH0624** [comment]
![1730710370273](https://github.com/user-attachments/assets/1ffc98c1-ef67-4925-a163-fafaf28ed57d)

**Comment by gfzhou** [comment]
This warning can be safely ignored.
